name: dartminator
description: Dart gRPC server and client
publish_to: none

environment:
  sdk: 2.15.0

dependencies: 
  faker: ^2.0.0
  grpc: ^3.0.2
  logger: ^1.1.0
dev_dependencies: 
  lints: ^1.0.1
